spring.application.name=secondhand

# اتصال به یک فایل SQLite که در ریشه‌ی پروژه ساخته می‌شود
spring.datasource.url=jdbc:sqlite:secondhand.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# ساخت خودکار جدول‌ها از روی کلاس‌ها و نمایش SQL در کنسول
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect